```{r}
library(readxl)
library(dplyr)
library(openxlsx)
library(lme4)
library(lmerTest)
library(Matrix)
library(mice)
library(metafor)
```

#Defining functions that will be used later
```{r}
fit_poisson_glm <- function(subdata) {
  # Fit the Poisson GLM
  glm_model <- glm(Total.ST.min ~ offset(log(Pickups)) + log(lag_TSM) + Intervention + weekday, family = "poisson", data = subdata)
  return(summary(glm_model))
}

process_data <- function(dataset) {
  summaries <- list()
  for(i in unique(dataset$pseudo_id)) {
    subdata <- dataset %>% filter(pseudo_id == i)
    if(nrow(subdata) > 1) {
      summaries[[as.character(i)]] <- fit_poisson_glm(subdata)
    } else {
      summaries[[as.character(i)]] <- NA
    }
  }
  summary_table <- data.frame(pseudo_id=character(),
                              beta_0=numeric(), 
                              beta_0_se=numeric(),
                              beta_1=numeric(), 
                              beta_1_se=numeric(),
                              beta_2=numeric(), 
                              beta_2_se=numeric(),
                              beta_3=numeric(), 
                              beta_3_se=numeric(),
                              stringsAsFactors=FALSE)
  for(i in names(summaries)) {
    #if (!is.na(summaries[[i]])) {
      model_coef <- coef(summaries[[i]])
      coef_se <- sqrt(diag(vcov(summaries[[i]])))
      summary_table <- rbind(summary_table, data.frame(pseudo_id=i,
                                                       beta_0=model_coef[1], 
                                                       beta_0_se=coef_se[1],
                                                       beta_1=model_coef[2], 
                                                       beta_1_se=coef_se[2],
                                                       beta_2=model_coef[3], 
                                                       beta_2_se=coef_se[3],
                                                       beta_3=model_coef[4], 
                                                       beta_3_se=coef_se[4]))
    #}
  }
  
  return(summary_table)
}

meta_analysis <- function(estimates_df) {
  estimates_df$weight_beta_0 <- 1 / (estimates_df$beta_0_se^2)
  estimates_df$weight_beta_1 <- 1 / (estimates_df$beta_1_se^2)
  estimates_df$weight_beta_2 <- 1 / (estimates_df$beta_2_se^2)
  estimates_df$weight_beta_3 <- 1 / (estimates_df$beta_3_se^2)
  
  beta_0_meta <- sum(estimates_df$beta_0 * estimates_df$weight_beta_0) / sum(estimates_df$weight_beta_0)
  beta_1_meta <- sum(estimates_df$beta_1 * estimates_df$weight_beta_1) / sum(estimates_df$weight_beta_1)
  beta_2_meta <- sum(estimates_df$beta_2 * estimates_df$weight_beta_2) / sum(estimates_df$weight_beta_2)
  beta_3_meta <- sum(estimates_df$beta_3 * estimates_df$weight_beta_3) / sum(estimates_df$weight_beta_3)
  
  beta_0_se_meta <- sqrt(1 / sum(estimates_df$weight_beta_0))
  beta_1_se_meta <- sqrt(1 / sum(estimates_df$weight_beta_1))
  beta_2_se_meta <- sqrt(1 / sum(estimates_df$weight_beta_2))
  beta_3_se_meta <- sqrt(1 / sum(estimates_df$weight_beta_3))
  
  meta_estimates <- c(beta_0_meta, beta_1_meta, beta_2_meta, beta_3_meta)
  se_meta_estimates <- c(beta_0_se_meta, beta_1_se_meta, beta_2_se_meta, beta_3_se_meta)
 
    return(data.frame(
    Parameter = c("beta_0", "beta_1", "beta_2", "beta_3"),
    Meta.Estimate = meta_estimates,
    Std.Error = se_meta_estimates
  ))
}

hypothesis_test <- function(estimate_summary, beta_num, alpha=0.05){
  z_score <- estimate_summary$Meta.Estimate[beta_num] / estimate_summary$Std.Error[beta_num]
  p_value <- 2 * (1 - pnorm(abs(z_score)))
  print(z_score)
  if(p_value < alpha) {
    print("It is statistically significant at alpha = 0.05.")
  } else {
    print("It is not statistically significant at alpha = 0.05.")
  }
}

```

#Data Processing
```{r}
data <- read_excel("final_full_data.xlsx")
# Checking the type of variables
str(data)
columns_to_convert <- c("Pickups", "workmate", "academic.talk", "non.academic", 
                        "pets", "sex", "age", "course.credit", 
                        "country.degree", "job", "siblings", 
                        "apps", "devices")
# Converting variables from chr to num
for (col in columns_to_convert) {
  data[[col]] <- as.numeric(data[[col]])
}
# Double check
str(data)

# Get subdata for Intervention A
data_A <- data %>% 
  filter(Treatment == "A")
data_A$Intervention <- ifelse(data_A$Phase == 'Treatment', 1, 0)
data_A <- data_A %>% 
  group_by(pseudo_id) %>%
  mutate(lag_TSM = lag(Total.ST.min, default = NA)) %>%
  ungroup()
# Removing data of id who does not have any treatment minute data at all, and who only have treatment data
data_A_cleaned <- data_A %>% 
  filter(!pseudo_id %in% c(2520, 6759, 8622, 9680, 9285))

# Get subdata for Intervention B
data_B <- data %>% 
  filter(Treatment == "B")
data_B$Intervention <- ifelse(data_B$Phase == 'Treatment', 1, 0)
data_B <- data_B %>% 
  group_by(pseudo_id) %>%
  mutate(lag_TSM = lag(Total.ST.min, default = NA)) %>%
  ungroup()
# Removing data of id who does not have any treatment minute data at all, and who only have treatment data
data_B_cleaned <- data_B %>% 
  filter(!pseudo_id %in% c(2880))
```

#Meta-learning for different individuals
```{r}
# Generating the meta estimates information for  A and B
summary_A = process_data(data_A_cleaned)
summary_B = process_data(data_B_cleaned)
meta_estimates_A <- meta_analysis(summary_A)
meta_estimates_B <- meta_analysis(summary_B)
print(meta_estimates_A)
print(meta_estimates_B)

# Do hypothesis test for Intervention
hypothesis_test(meta_estimates_A, 3)
hypothesis_test(meta_estimates_B, 3)
```

#Meta-learning for different interventions
```{r}
# Generating glm model for group A and B
model_A <- glm(Total.ST.min ~ offset(log(Pickups)) + log(lag_TSM) + Intervention + weekday + pets + sex + age + course.credit + siblings + apps + devices +procrastination.score, family = "poisson", data = data_A)

model_B <- glm(Total.ST.min ~ offset(log(Pickups)) + log(lag_TSM) + Intervention + weekday + pets + sex + age + course.credit + siblings + apps + devices +procrastination.score, family = "poisson", data = data_B)

# Getting coefficients from A and B
coef_A <- summary(model_A)$coefficients
coef_B <- summary(model_B)$coefficients

# Combining coefficients info of A and B
meta_data_A <- data.frame(
  estimate = coef_A[, 1],
  se = coef_A[, 2],
  variable = rownames(coef_A),
  model = "A"
)

meta_data_B <- data.frame(
  estimate = coef_B[, 1],
  se = coef_B[, 2],
  variable = rownames(coef_B),
  model = "B"
)
meta_data <- rbind(meta_data_A, meta_data_B)

meta_results <- list()
for (var in unique(meta_data$variable)) {
  data_subset <- meta_data[meta_data$variable == var, ]
  meta_results[[var]] <- rma(yi = estimate, sei = se, method = "FE", data = data_subset)
}

meta_estimates <- sapply(meta_results, function(res) coef(res))
meta_se <- sapply(meta_results, function(res) sqrt(diag(vcov(res))))

meta_results_df <- data.frame(
  Parameter = c('beta_0','beta_1','beta_2','beta_3','beta_4','beta_5','beta_6','beta_7','beta_8','beta_9','beta_10','beta_11'),
  Meta.Estimate = meta_estimates,
  Std.Error = meta_se,
  Z.score = meta_estimates/meta_se,
  p.value = 2 * (1 - pnorm(abs(meta_estimates/meta_se)))
)
rownames(meta_results_df) <- NULL
print(meta_results_df)
```

#Generating glm using full data
```{r}
data_combine <- rbind(data_A,data_B)
model_full <- glm(Total.ST.min ~ offset(log(Pickups)) + log(lag_TSM) + Intervention + weekday + pets + sex + age + course.credit + siblings + apps + devices +procrastination.score, family = "poisson", data = data_combine)
summary(model_full)
```

#Generating linear mixed effect model for comparison
```{r}
model_mixed <- lmer(Total.ST.min ~ offset(log(Pickups)) + log(lag_TSM) + Intervention + weekday + pets + sex + age + course.credit + siblings + apps + devices + procrastination.score + (1 | pseudo_id), data = data_combine)
summary(model_mixed)
```

#Generating glm for compliance condition
```{r}
model_compliance <- glm(compliance ~ log(lag_TSM) + weekday + pets + sex + age + course.credit + siblings + apps + devices +procrastination.score, family = "binomial", data = data_combine)
summary(model_compliance)
```
